### ISSUE TITLE
В файл README.md добавить новую строку о погоде за окном

### ISSUE THREAD

**Issue by ShaoYoung** [ShaoYoung/git_in_depth#1]
Новое задание

**Comment by ShaoYoung** [comment]
Задачу надо выполнить в отдельной ветке, потом pull request и перевести задачу обратно на меня.
Как добавить доступ к репозиторию, кроме ветки master, я пока не нашёл.

**Comment by ShvonderSiN** [comment]
Выполнено

**Comment by ShaoYoung** [comment]
Принято. У нас тоже прохладно, только пока без дождя.
